<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\Http\Controllers\Controller;
use App\State;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CityController extends Controller
{
    /**
     * Create a new controller instance
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of cities
     */
    public function index(Request $request)
    {
        $query = City::with('state');

        // Filter by state
        if ($request->has('state') && $request->state !== '') {
            $query->where('state_id', $request->state);
        }

        // Filter by status
        if ($request->has('status') && $request->status !== '') {
            if ($request->status === 'active') {
                $query->where('is_active', true);
            } elseif ($request->status === 'inactive') {
                $query->where('is_active', false);
            }
        }

        // Search
        if ($request->has('search') && $request->search !== '') {
            $query->where(function ($q) use ($request) {
                $q->where('name', 'like', '%'.$request->search.'%')
                    ->orWhere('description', 'like', '%'.$request->search.'%')
                    ->orWhereHas('state', function ($stateQuery) use ($request) {
                        $stateQuery->where('name', 'like', '%'.$request->search.'%');
                    });
            });
        }

        $cities = $query->orderBy('city_name', 'asc')->paginate(15);
        $states = State::active()->orderBy('name')->get();

        return view('admin.cms.cities.index', compact('cities', 'states'));
    }

    /**
     * Show the form for creating a new city
     */
    public function create()
    {
        $states = State::active()->orderBy('name')->get();

        return view('admin.cms.cities.create', compact('states'));
    }

    /**
     * Store a newly created city
     */
    public function store(Request $request)
    {
        $request->validate([
            'city_name' => 'required|string|max:255',
            'state_id' => 'required|exists:states,id',
            'description' => 'nullable|string',
            'is_active' => 'boolean',
            'meta_title' => 'nullable|string|max:255',
            'meta_description' => 'nullable|string|max:500',
        ]);

        $data = $request->all();
        // Handle both 'name' and 'city_name' for backward compatibility
        if (isset($data['name']) && !isset($data['city_name'])) {
            $data['city_name'] = $data['name'];
            unset($data['name']);
        }
        // Slug will be auto-generated by model if not provided
        if (empty($data['slug'])) {
            $data['slug'] = null; // Let model generate it
        }
        $data['is_active'] = $request->has('is_active');

        City::create($data);

        return redirect()->route('admin.cities.index')
            ->with('success', 'City created successfully!');
    }

    /**
     * Display the specified city
     */
    public function show(City $city)
    {
        $city->load(['state', 'areas', 'pages']);

        return view('admin.cms.cities.show', compact('city'));
    }

    /**
     * Show the form for editing the specified city
     */
    public function edit(City $city)
    {
        $states = State::active()->orderBy('name')->get();

        return view('admin.cms.cities.edit', compact('city', 'states'));
    }

    /**
     * Update the specified city
     */
    public function update(Request $request, City $city)
    {
        $request->validate([
            'city_name' => 'required|string|max:255',
            'state_id' => 'required|exists:states,id',
            'description' => 'nullable|string',
            'is_active' => 'boolean',
            'meta_title' => 'nullable|string|max:255',
            'meta_description' => 'nullable|string|max:500',
        ]);

        $data = $request->all();
        // Handle both 'name' and 'city_name' for backward compatibility
        if (isset($data['name']) && !isset($data['city_name'])) {
            $data['city_name'] = $data['name'];
            unset($data['name']);
        }
        // Only regenerate slug if city_name changed and slug is empty
        if ($city->isDirty('city_name') && empty($data['slug'])) {
            $data['slug'] = null; // Let model regenerate it
        }
        $data['is_active'] = $request->has('is_active');

        $city->update($data);

        return redirect()->route('admin.cities.index')
            ->with('success', 'City updated successfully!');
    }

    /**
     * Remove the specified city
     */
    public function destroy(City $city)
    {
        if ($city->areas()->count() > 0) {
            return redirect()->route('admin.cities.index')
                ->with('error', 'Cannot delete city with associated areas!');
        }

        $city->delete();

        return redirect()->route('admin.cities.index')
            ->with('success', 'City deleted successfully!');
    }

    /**
     * Get cities by state (AJAX)
     */
    public function getByState(Request $request)
    {
        $stateId = $request->get('state_id');
        $cities = City::where('state_id', $stateId)
            ->active()
            ->orderBy('city_name')
            ->get(['id', 'city_name']);

        // Map to ensure consistent response format
        $cities = $cities->map(function($city) {
            return [
                'id' => $city->id,
                'city_name' => $city->city_name,
                'name' => $city->city_name, // Alias for compatibility
            ];
        });

        return response()->json($cities);
    }
}
